trigger: none

resources:
  packages:
   - package: pac1
     type: Nuget
     connection: github_pat
     name: nugetTest/OctocatApp
     version: 1.0.1
     trigger: true
    
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool:
        name: Default
       steps:
        - getPackage: pac1
     
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
